language: node_js

node_js:
  - node

before_script:
  - npm install -g codeclimate-test-reporter sequelize-cli
  - psql -c 'drop database if exists eventdb_test;' -U postgres
  - psql -c 'create database eventdb_test;' -U postgres
  - npm run migrate:test

services:
  - postgresql

script:
  - npm install node-pre-gyp && npm test

after_success:
  - npm run coveralls:report
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info