
export const ADD_USER_SUCCESS = 'ADD_USER-SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER-SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';

